# Generated by Django 5.2.15 on 2026-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(choices=[('+211', 'South Sudan (+211)'), ('+254', 'Kenya (+254)'), ('+256', 'Uganda (+256)'), ('+251', 'Ethiopia (+251)'), ('+249', 'Sudan (+249)'), ('+243', 'DR Congo (+243)'), ('+236', 'Central African Republic (+236)')], default='+211', max_length=8),
        ),
    ]
