# Generated by Django 5.2.15 on 2026-08-14 17:39

import core.translations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=core.translations.language_choices, default='en', max_length=24),
        ),
    ]
