# Generated by Django 5.2.17 on 2026-08-18 10:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_migrate_phone_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=32, null=True, region=None, unique=True),
        ),
    ]
