# Generated by Django 5.2.15 on 2026-08-14 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('ethnic_group', models.CharField(blank=True, max_length=80)),
                ('county', models.CharField(max_length=120)),
                ('payam', models.CharField(blank=True, max_length=120)),
                ('boma', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('trust_score', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ('county', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(max_length=120)),
                ('detail', models.CharField(max_length=240)),
                ('accent', models.CharField(default='teal', max_length=20)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ('-happened_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('alert', 'Alert'), ('action', 'Action')], default='info', max_length=16)),
                ('action_url', models.CharField(blank=True, max_length=240)),
                ('is_read', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.community')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholder_type', models.CharField(choices=[('government', 'Government'), ('ngo', 'Non-government org.'), ('community_leader', 'Local community leader'), ('religious_leader', 'Religious leader'), ('other', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('communities', models.ManyToManyField(blank=True, related_name='stakeholders', to='core.community')),
            ],
            options={
                'ordering': ('stakeholder_type', 'name'),
            },
        ),
    ]
