# Generated by Django 5.2.15 on 2026-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='holder_id',
            field=models.CharField(blank=True, editable=False),
        ),
    ]
