# Generated by Django 5.2.15 on 2026-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stakeholder_holder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='activey',
            field=models.BooleanField(default=True),
        ),
    ]
