# Generated by Django 5.2.15 on 2026-08-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stakeholder_activey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='activey',
        ),
    ]
