# Generated by Django 5.2.15 on 2026-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_stakeholder_activey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_language', models.CharField(default='en', max_length=24)),
                ('target_language', models.CharField(db_index=True, max_length=24)),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(default='openai', max_length=40)),
            ],
            options={
                'ordering': ('target_language', 'source_hash'),
                'constraints': [models.UniqueConstraint(fields=('source_hash', 'target_language'), name='unique_translation_source_target')],
            },
        ),
    ]
