# Generated by Django 5.2.15 on 2026-08-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('grain', 'Grain'), ('livestock', 'Livestock'), ('fish', 'Fish'), ('crafts', 'Crafts'), ('services', 'Services'), ('other', 'Other')], default='grain', max_length=24)),
                ('quantity', models.CharField(max_length=80)),
                ('offer_type', models.CharField(choices=[('sell', 'Selling'), ('buy', 'Buying'), ('exchange', 'Exchange')], max_length=16)),
                ('location', models.CharField(max_length=160)),
                ('contact_method', models.CharField(help_text='Phone, USSD callback, or voice message', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('completed', 'Completed'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_offers', to='core.community')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TradeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('accepted', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_connections', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='trade.tradeoffer')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('offer', 'requester')},
            },
        ),
    ]
