# Generated by Django 5.2.15 on 2026-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_tradelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeconnection',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
