# Generated by Django 5.2.15 on 2026-08-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_tradeconnection_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trade_products/'),
        ),
    ]
