# Generated by Django 5.2.15 on 2026-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridorresponse',
            name='negotiation_outcome',
            field=models.TextField(blank=True, help_text='Final community response after route negotiation. Required when negotiation is selected.'),
        ),
    ]
