# Generated by Django 5.2.15 on 2026-08-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('reporter_name', models.CharField(max_length=160)),
                ('reporter_contact', models.CharField(max_length=120)),
                ('conflict_type', models.CharField(choices=[('crop_damage', 'Crop damage'), ('water_access', 'Water access'), ('cattle_raiding', 'Cattle raiding'), ('boundary', 'Boundary dispute'), ('market', 'Market dispute'), ('other', 'Other')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('reported', 'Reported'), ('assessing', 'Assessing'), ('mediating', 'Mediating'), ('agreed', 'Agreement drafted'), ('resolved', 'Resolved'), ('referred', 'Referred')], db_index=True, default='reported', max_length=20)),
                ('resolution_summary', models.TextField(blank=True)),
                ('assigned_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conflicts', to=settings.AUTH_USER_MODEL)),
                ('community_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_a', to='core.community')),
                ('community_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_b', to='core.community')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('reported', 'Reported'), ('assessing', 'Assessing'), ('mediating', 'Mediating'), ('agreed', 'Agreement drafted'), ('resolved', 'Resolved'), ('referred', 'Referred')], max_length=20)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='conflicts.conflictcase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=24)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='conflicts.conflictcase')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_referrals', to='core.stakeholder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
