# Generated by Django 5.2.15 on 2026-08-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('dispute_types', models.JSONField(default=list)),
                ('dispute_other', models.CharField(blank=True, max_length=160)),
                ('date_signed', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signing_location', models.CharField(max_length=200)),
                ('mediators', models.TextField(help_text='Names and affiliation')),
                ('key_terms', models.JSONField(default=list)),
                ('key_terms_other', models.CharField(blank=True, max_length=200)),
                ('detailed_terms', models.TextField()),
                ('committee_a_name', models.CharField(max_length=160)),
                ('committee_a_contact', models.CharField(max_length=120)),
                ('committee_b_name', models.CharField(max_length=160)),
                ('committee_b_contact', models.CharField(max_length=120)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('breached', 'Breached'), ('fulfilled', 'Fulfilled')], default='active', max_length=24)),
                ('escalation_contact', models.CharField(max_length=200)),
                ('community_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_a', to='core.community')),
                ('community_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_b', to='core.community')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_signed', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AgreementNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'Phone / SMS')], max_length=12)),
                ('destination', models.CharField(max_length=160)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='queued', max_length=80)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='agreements.agreement')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_notices', to='core.stakeholder')),
            ],
            options={
                'ordering': ('stakeholder__stakeholder_type', 'stakeholder__name'),
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='stakeholders',
            field=models.ManyToManyField(related_name='agreements', through='agreements.AgreementNotice', to='core.stakeholder'),
        ),
    ]
