# Generated by Codex on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="signing_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signing_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
