# Generated by Django 5.2.15 on 2026-08-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreement_signing_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementnotice',
            name='destination',
        ),
    ]
