# Generated by Django 5.2.15 on 2026-08-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_remove_agreementnotice_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementnotice',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Phone / SMS')], default='Email', max_length=12),
        ),
    ]
