# Generated by Django 5.2.15 on 2026-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_alter_agreementnotice_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementnotice',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'Phone / SMS')], default='Email', max_length=12),
        ),
    ]
