# Generated by Django 5.2.15 on 2026-08-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_alter_agreementnotice_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementnotice',
            name='destination',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
